CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON "django_content_type" ("app_label", "model");
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "last_name" varchar(150) NOT NULL);
CREATE TABLE "layouts_maxplacesnumber" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NULL, "amount" integer NULL, "direction" integer NOT NULL, "layout_id" integer NOT NULL REFERENCES "layouts_layout" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "layouts_priority" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "value" real NOT NULL, "order" integer NOT NULL, "layout_id" integer NOT NULL REFERENCES "layouts_layout" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "layouts_maxplacesnumber_layout_id_c0c633e0" ON "layouts_maxplacesnumber" ("layout_id");
CREATE INDEX "layouts_priority_layout_id_c1abebe7" ON "layouts_priority" ("layout_id");
CREATE TABLE "layouts_placesnumber" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "amount" integer NOT NULL, "in_max_places_id" integer NOT NULL REFERENCES "layouts_maxplacesnumber" ("id") DEFERRABLE INITIALLY DEFERRED, "layout_id" integer NOT NULL REFERENCES "layouts_layout" ("id") DEFERRABLE INITIALLY DEFERRED, "out_max_places_id" integer NOT NULL REFERENCES "layouts_maxplacesnumber" ("id") DEFERRABLE INITIALLY DEFERRED, "required" bool NOT NULL);
CREATE INDEX "layouts_placesnumber_in_max_places_id_690f3719" ON "layouts_placesnumber" ("in_max_places_id");
CREATE INDEX "layouts_placesnumber_layout_id_614b7e02" ON "layouts_placesnumber" ("layout_id");
CREATE INDEX "layouts_placesnumber_out_max_places_id_3744fe5d" ON "layouts_placesnumber" ("out_max_places_id");
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE "layouts_datepriority" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "value" real NOT NULL, "order" integer NOT NULL, "in_date_id" integer NOT NULL REFERENCES "layouts_maxplacesnumber" ("id") DEFERRABLE INITIALLY DEFERRED, "layout_id" integer NOT NULL REFERENCES "layouts_layout" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "layouts_datepriority_in_date_id_d2a256b6" ON "layouts_datepriority" ("in_date_id");
CREATE INDEX "layouts_datepriority_layout_id_41f2b06e" ON "layouts_datepriority" ("layout_id");
CREATE TABLE "layouts_layout" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "min_days" integer NOT NULL, "max_days" integer NOT NULL, "width" integer NOT NULL, "start_date" date NULL, "end_date" date NULL, "filename" varchar(255) NULL, "edit_token" varchar(36) NULL, "last_token_update" datetime NULL, "duration_limit" integer NOT NULL);
CREATE TABLE "layouts_outoforderplacesnumber" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "amount" integer NOT NULL, "in_date_id" integer NOT NULL REFERENCES "layouts_maxplacesnumber" ("id") DEFERRABLE INITIALLY DEFERRED, "layout_id" integer NOT NULL REFERENCES "layouts_layout" ("id") DEFERRABLE INITIALLY DEFERRED, "out_date_id" integer NOT NULL REFERENCES "layouts_maxplacesnumber" ("id") DEFERRABLE INITIALLY DEFERRED, "auto_changed" bool NOT NULL);
CREATE INDEX "layouts_outoforderplacesnumber_in_date_id_124b709c" ON "layouts_outoforderplacesnumber" ("in_date_id");
CREATE INDEX "layouts_outoforderplacesnumber_layout_id_9415f536" ON "layouts_outoforderplacesnumber" ("layout_id");
CREATE INDEX "layouts_outoforderplacesnumber_out_date_id_1404209e" ON "layouts_outoforderplacesnumber" ("out_date_id");
CREATE TABLE "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" datetime NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
