# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_days', models.IntegerField()),
                ('max_days', models.IntegerField()),
                ('width', models.IntegerField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxPlacesNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('direction', models.IntegerField(choices=[(0, 'in'), (1, 'out')], default=0)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout')),
            ],
        ),
        migrations.CreateModel(
            name='PlacesNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('in_max_places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_max_places', to='layouts.MaxPlacesNumber')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout')),
                ('out_max_places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_max_places', to='layouts.MaxPlacesNumber')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('order', models.IntegerField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout')),
            ],
        ),
    ]
