# Generated by Django 2.0.1 on 2018-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesnumber',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
