# Generated by Django 2.0.1 on 2018-01-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_placesnumber_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
