# Generated by Django 2.0.1 on 2018-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_layout_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='edit_token',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='last_token_update',
            field=models.DateTimeField(null=True),
        ),
    ]
