# Generated by Django 2.0.1 on 2018-02-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0004_auto_20180122_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('order', models.IntegerField()),
                ('in_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.MaxPlacesNumber')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout')),
            ],
        ),
    ]
