# Generated by Django 2.0.1 on 2018-02-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0005_datepriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfOrderPlacesNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('in_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_date', to='layouts.MaxPlacesNumber')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout')),
                ('out_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_date', to='layouts.MaxPlacesNumber')),
            ],
        ),
    ]
