# Generated by Django 2.0.1 on 2018-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0006_outoforderplacesnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='duration_limit',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
