# Generated by Django 2.0.1 on 2018-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0008_outoforderplacesnumber_auto_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='update_from_file_date',
            field=models.DateTimeField(null=True),
        ),
    ]
