# Generated by Django 2.0.1 on 2018-04-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0009_layout_update_from_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='update_from_file_date',
            field=models.DateField(null=True),
        ),
    ]
